# Generated by Django 4.1.1 on 2022-10-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
